### ISSUE TITLE
Summary - Meets Expectations

### ISSUE THREAD

**Issue by tbergen1** [JohnL01/sql-scratch-capstone-turn-in#5]
Overall, you did a good job on this project.  You answered every question correctly and demonstrated an understanding of SQL by generating queries that would yield these correct results.  Your queries followed the style guide fairly well and only fell short with consistency of keyword capitalization.  You were also missing answers to a few questions, which you may want to go back and answer.  Other than that you did a good job.

**Comment by JohnL01** [comment]
Thanks for the feedback. I enjoyed the course and am already using what I've learned.
